/* =========================================
   course-data.js — 비아이매트릭스 아카데미
   보유 영상 기반 강의 데이터 (20개)
   ========================================= */

const COURSES = [

  /* ── i-META View · OLAP 조회 ── */
  {
    id: 1,
    product: "i-META View",
    title: "드래그만으로 지점별 매출 실적을 내가 원하는 항목으로 조회할 수 있어요",
    report_title: "지점별 매출 실적(List) - 기본",
    industry: ["retail", "finance", "manufacturing", "public"],
    role: ["analyst"],
    feature: ["olap"],
    level: "lv1",
    duration: "1분",
    price: 90000,
    outcome: "데이터 파일에서 보고싶은 항목을 화면에 끌어다 놓으면 화면에 데이터가 바로 조회돼요.",
    step: "OLAP · 기본 조회",
    thumbnail: "assets/images/thumb-olap.jpg"
  },
  {
    id: 2,
    product: "i-META View",
    title: "조회한 데이터를 내 업무에 맞게 가공할 수 있어요",
    report_title: "지점별 매출 실적(List) - 응용",
    industry: ["retail", "finance", "manufacturing", "public"],
    role: ["analyst"],
    feature: ["olap"],
    level: "lv1",
    duration: "4분",
    price: 90000,
    outcome: "정렬·필터·소계·화면 재구성(단위 변환)·계절 컬럼 추가까지, 별도 엑셀 작업 없이 조회 화면에서 바로 처리할 수 있어요.",
    step: "OLAP · 데이터 가공",
    thumbnail: "assets/images/thumb-olap.jpg"
  },
  {
    id: 3,
    product: "i-META View",
    title: "상품 정보를 피벗 형태로 배치해 다양한 관점으로 매출을 분석할 수 있어요",
    report_title: "상품별 매출 분석(CrossTab) - 기본",
    industry: ["retail", "manufacturing"],
    role: ["analyst"],
    feature: ["olap"],
    level: "lv1",
    duration: "2분",
    price: 90000,
    outcome: "행과 열에 원하는 항목을 끌어다 놓으면 상품별·매장별 매출 순위 교차표가 바로 나와요.",
    step: "OLAP · CrossTab 기본",
    thumbnail: "assets/images/thumb-olap.jpg"
  },
  {
    id: 4,
    product: "i-META View",
    title: "피벗 분석의 심화 기능으로 상품 매출을 깊이 있게 파고들 수 있어요",
    report_title: "상품별 매출 분석(CrossTab) - 응용",
    industry: ["retail", "manufacturing"],
    role: ["analyst"],
    feature: ["olap"],
    level: "lv1",
    duration: "3분",
    price: 90000,
    outcome: "구조 변경(소계 생성)·그룹핑·정렬·필터·비교 지표·배경 데이터 확인까지 보고서 한 장에서 전부 처리할 수 있어요.",
    step: "OLAP · CrossTab 응용",
    thumbnail: "assets/images/thumb-olap.jpg"
  },
  {
    id: 5,
    product: "i-META View",
    title: "숫자로 보던 매출 데이터의 추세를 추가하여 흐름과 추이를 한눈에 볼 수 있어요",
    report_title: "기간별 매출 추이 현황(Chart) - 기본",
    industry: ["retail", "finance", "manufacturing", "public"],
    role: ["analyst", "finance"],
    feature: ["olap", "dashboard"],
    level: "lv1",
    duration: "1분",
    price: 90000,
    outcome: "수치로 보면 찾기 어렵던 항목과 추세 유형을 시각화하고 기준·범위를 조정해 추이를 쉽게 파악할 수 있어요.",
    step: "OLAP · 차트 기본",
    thumbnail: "assets/images/thumb-dashboard.jpg"
  },
  {
    id: 6,
    product: "i-META View",
    title: "차트 유형·색상·조건 범위·계열을 바꿔 내 보고서에 딱 맞는 차트를 만들 수 있어요",
    report_title: "기간별 매출 추이 현황(Chart) - 응용",
    industry: ["retail", "finance", "manufacturing", "public"],
    role: ["analyst", "finance"],
    feature: ["olap", "dashboard"],
    level: "lv1",
    duration: "2분",
    price: 90000,
    outcome: "다양한 속성 설정만으로 차트의 모양과 전달하는 데이터 범위를 자유롭게 조절할 수 있어요.",
    step: "OLAP · 차트 응용",
    thumbnail: "assets/images/thumb-dashboard.jpg"
  },
  {
    id: 7,
    product: "i-META View",
    title: "데이터 다운로드 없이 자동 연동된 엑셀 보고서로 매장별 매출 현황을 만들 수 있어요",
    report_title: "매장별 매출 현황",
    industry: ["retail"],
    role: ["analyst"],
    feature: ["report"],
    level: "lv1",
    duration: "6분",
    price: 90000,
    outcome: "빈 엑셀에 데이터를 결합하여 기간만 선택하면 매장별 매출 합계·기획·계산·각종 서식까지 한 번에 완성돼요.",
    step: "Report · 엑셀 연동",
    thumbnail: "assets/images/thumb-report.jpg"
  },

  /* ── i-MATRIX · 보고서 자동화 ── */
  {
    id: 8,
    product: "i-MATRIX",
    title: "매일 다운로드해야 피벗 돌리던 작업을 기간만 선택하면 자동 완성되는 엑셀 보고서로 만들 수 있어요",
    report_title: "상품별 매출 실적 현황",
    industry: ["retail", "manufacturing"],
    role: ["analyst"],
    feature: ["report"],
    level: "lv2",
    duration: "3분",
    price: 220000,
    outcome: "데이터가 연동된 엑셀에 피벗테이블과 슬라이서 필터를 추가하면 상품별 매출 분석 보고서가 완성돼요.",
    step: "G-MATRIX · 보고서 자동화",
    thumbnail: "assets/images/thumb-report.jpg"
  },
  {
    id: 9,
    product: "i-MATRIX",
    title: "매일 영업 보고서에 붙여 넣던 수작업을 엑셀 밖에서 처리하여 자동으로 만들 수 있어요",
    report_title: "영업 실적 보고서",
    industry: ["retail", "finance", "manufacturing"],
    role: ["analyst", "finance"],
    feature: ["epa", "report"],
    level: "lv2",
    duration: "14분",
    price: 220000,
    outcome: "엑셀에서 영업 실적을 수식·자동화·차트까지 3가지 기능으로 엑셀 데이터와 연동 전환해요. 개발자에게 요청하지 않아도 돼요.",
    step: "G-MATRIX · EPA 보고서",
    thumbnail: "assets/images/thumb-epa.jpg"
  },
  {
    id: 20,
    product: "i-MATRIX",
    title: "엑셀에서 매장별 매출 계획을 직접 수정하고 DB에 저장까지 되는 관리 화면을 만들 수 있어요",
    report_title: "매장별 매출 계획 관리",
    industry: ["retail", "manufacturing"],
    role: ["finance", "analyst"],
    feature: ["uiux"],
    level: "lv2",
    duration: "9분",
    price: 220000,
    outcome: "DB 연결 시트를 자동으로 생성하고 저장·조회 기능을 연결한 엑셀이 실무 데이터 관리 도구가 돼요.",
    step: "G-MATRIX · 관리화면",
    thumbnail: "assets/images/thumb-uiux.jpg"
  },

  /* ── i-AUD · 통합 보고서 ── */
  {
    id: 10,
    product: "i-AUD",
    title: "전월·전년 비교와 고객 등급별 실적, 표 하나에 다 담은 통합 보고서를 엑셀로 직접 만들 수 있어요",
    report_title: "상품별 실적",
    industry: ["retail", "finance"],
    role: ["analyst"],
    feature: ["epa", "report"],
    level: "lv2",
    duration: "13분",
    price: 220000,
    outcome: "다양한 분석 관점을 엑셀로 설계하면 레이아웃과 수식이 틀에 맞게 자동 반영돼요. 개발자 없이 완성돼요.",
    step: "AUD · 통합 보고서",
    thumbnail: "assets/images/thumb-epa.jpg"
  },
  {
    id: 11,
    product: "i-AUD",
    title: "영업 실적 대시보드를 매일 붙여 넣던 작업 없이 데이터가 연결된 화면으로 직접 만들 수 있어요",
    report_title: "매출 현황",
    industry: ["retail", "finance", "manufacturing"],
    role: ["analyst", "finance"],
    feature: ["epa", "report", "dashboard"],
    level: "lv2",
    duration: "16분",
    price: 220000,
    outcome: "엑셀 시트를 따로 쓰지 않고 이미지·차트를 한 화면에 연결해 완성해요.",
    step: "AUD · 매출 대시보드",
    thumbnail: "assets/images/thumb-dashboard.jpg"
  },
  {
    id: 12,
    product: "i-AUD",
    title: "매달 손으로 범위 조정하던 엑셀 보고서를 기간만 선택하면 자동 완성되는 정기 보고서로 만들 수 있어요",
    report_title: "고객 등급별 매출 추이",
    industry: ["retail", "finance"],
    role: ["marketing"],
    feature: ["report"],
    level: "lv2",
    duration: "7분",
    price: 220000,
    outcome: "기준에 맞는 엑셀 양식을 구성하면 선택한 기간의 데이터가 화면에 자동 표시되는 보고서가 완성돼요.",
    step: "AUD · 정기 보고서",
    thumbnail: "assets/images/thumb-report.jpg"
  },
  {
    id: 13,
    product: "i-AUD",
    title: "복잡한 엑셀 작업 없이 조회된 데이터를 채워 지정 점포별 매출 보고서를 만들 수 있어요",
    report_title: "주요 점포별 매출 실적 현황",
    industry: ["retail"],
    role: ["finance", "analyst"],
    feature: ["report"],
    level: "lv2",
    duration: "10분",
    price: 220000,
    outcome: "화면에서 선택만 하고 자동화 기능을 연결하면 점포별 보고서가 완성돼요.",
    step: "AUD · 점포별 보고서",
    thumbnail: "assets/images/thumb-report.jpg"
  },

  /* ── i-AUD · 고객 대시보드 ── */
  {
    id: 14,
    product: "i-AUD",
    title: "고객별 매출 대시보드를 엑셀로 직접 만들 수 있어요",
    report_title: "고객별 매출 현황(기본)",
    industry: ["retail", "finance"],
    role: ["marketing"],
    feature: ["epa", "dashboard"],
    level: "lv1",
    duration: "7분",
    price: 90000,
    outcome: "회원카드·성별·연령·부서·업태 등의 차트를 엑셀로 설계하면 레이아웃·수식·그래프로 자동 연결돼요.",
    step: "AUD · 고객 대시보드 기본",
    thumbnail: "assets/images/thumb-dashboard.jpg"
  },
  {
    id: 15,
    product: "i-AUD",
    title: "차트 막대를 클릭하면 해당 고객의 상세 데이터가 팝업으로 열리는 기능을 코딩 없이 추가할 수 있어요",
    report_title: "고객별 매출 현황(응용)",
    industry: ["retail", "finance"],
    role: ["marketing"],
    feature: ["epa", "dashboard"],
    level: "lv1",
    duration: "4분",
    price: 90000,
    outcome: "이벤트 콘솔을 설정하는 것만으로 차트와 상세 데이터가 연결돼요. 개발자 없이 인터랙티브 보고서가 완성돼요.",
    step: "AUD · 고객 대시보드 응용",
    thumbnail: "assets/images/thumb-dashboard.jpg"
  },

  /* ── i-AUD · 관리화면 (UI/UX) ── */
  {
    id: 16,
    product: "i-AUD",
    title: "코딩 없이 고객 정보를 직접 조회·수정·삭제까지 할 수 있는 관리 화면을 만들 수 있어요",
    report_title: "고객 정보 관리",
    industry: ["retail", "finance"],
    role: ["marketing"],
    feature: ["uiux"],
    level: "lv1",
    duration: "6분",
    price: 90000,
    outcome: "데이터 처리 모듈을 설정하는 것만으로 변경 사항이 바로 저장되는 실무 관리 화면이 완성돼요.",
    step: "AUD · 고객 관리화면",
    thumbnail: "assets/images/thumb-uiux.jpg"
  },
  {
    id: 17,
    product: "i-AUD",
    title: "고객을 선택하면 해당 고객의 상세 매출 내역이 리스트로 연결되는 관리 화면을 만들 수 있어요",
    report_title: "고객별 매출 실적",
    industry: ["retail", "finance"],
    role: ["marketing"],
    feature: ["uiux"],
    level: "lv1",
    duration: "11분",
    price: 90000,
    outcome: "고객 정보와 매출 정보를 연결, 두 가지 데이터를 한 화면에서 조회·수정까지 할 수 있는 관리화면이 완성돼요.",
    step: "AUD · 매출 관리화면",
    thumbnail: "assets/images/thumb-uiux.jpg"
  },
  {
    id: 18,
    product: "i-AUD",
    title: "입력 폼과 목록을 연결해 임직원 정보를 편하게 수정·관리하는 화면을 코딩 없이 만들 수 있어요",
    report_title: "인사 관리",
    industry: ["retail", "finance", "manufacturing", "public"],
    role: ["analyst", "developer"],
    feature: ["uiux"],
    level: "lv2",
    duration: "12분",
    price: 220000,
    outcome: "근속년수 자동 계산, 직급 수 집계, 수정·조회까지 — 실무에서 바로 쓸 수 있는 관리 화면이 완성돼요.",
    step: "AUD · 인사 관리화면",
    thumbnail: "assets/images/thumb-uiux.jpg"
  },
  {
    id: 19,
    product: "i-AUD",
    title: "기간을 선택하면 매출 계획을 직접 상품 기준으로 분류하고 수정·저장까지 할 수 있는 화면을 만들 수 있어요",
    report_title: "매출 계획 입력",
    industry: ["retail", "finance", "manufacturing"],
    role: ["finance"],
    feature: ["epa", "uiux"],
    level: "lv2",
    duration: "14분",
    price: 220000,
    outcome: "매장·지역·유형·항목 교차 탭을 표 형태 그대로 직접 입력하고 저장할 수 있는 화면이 완성돼요.",
    step: "AUD · 계획 입력화면",
    thumbnail: "assets/images/thumb-uiux.jpg"
  }

];
